[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# log4j
> topicLinkUID=`187B27939C8A`


## log4j\.properties
> collapsed=`true`


### \# Root logger option<br/>log4j\.rootLogger=INFO, file, stdout  <br/><br/>\# Запись в лог файл<br/>\# Direct log messages to a log file <br/>log4j\.appender\.file=org\.apache\.log4j\.RollingFileAppender  <br/>log4j\.appender\.file\.File=logging\.log  <br/>log4j\.appender\.file\.MaxFileSize=10MB  <br/>log4j\.appender\.file\.MaxBackupIndex=10  <br/>log4j\.appender\.file\.layout=org\.apache\.log4j\.PatternLayout  <br/>log4j\.appender\.file\.layout\.ConversionPattern=%d\{yyyy\-MM\-dd HH:mm:ss\} %\-5p %c\{1\}:%L \- %m%n  <br/><br/>\# Вывод записей в консоль<br/>\# Direct log messages to stdout<br/>log4j\.appender\.stdout=org\.apache\.log4j\.ConsoleAppender  <br/>log4j\.appender\.stdout\.Target=System\.out  <br/>log4j\.appender\.stdout\.layout=org\.apache\.log4j\.PatternLayout  <br/>log4j\.appender\.stdout\.layout\.ConversionPattern=%d\{yyyy\-MM\-dd HH:mm:ss\} <br/>%\-5p %c\{1\}:%L \- %m%n  ern=%d\{yyyy\-MM\-dd HH:mm:ss\} %\-5p %c\{1\}:%L \- %m%n  
> align=`left`

- TOPIC
<pre>187B27939C8A</pre>
